services:
  crypto-dataviz:
    container_name: crypto-dataviz
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crypto-dataviz.entrypoints=web"
      - "traefik.http.routers.crypto-dataviz.rule=Host(`crypto-dataviz.guatanga.xyz`)"
      - "traefik.http.middlewares.crypto-dataviz-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.crypto-dataviz.middlewares=crypto-dataviz-https-redirect"
      # Secure Router setup
      - "traefik.http.routers.crypto-dataviz-secure.entrypoints=web-secure"
      - "traefik.http.routers.crypto-dataviz-secure.rule=Host(`crypto-dataviz.guatanga.xyz`)"
      - "traefik.http.routers.crypto-dataviz-secure.tls=true"
      - "traefik.http.routers.crypto-dataviz-secure.service=crypto-dataviz"
      - "traefik.http.routers.crypto-dataviz-secure.middlewares=secHeaders@file, autodetectContenttype@file"
      - "traefik.http.services.crypto-dataviz.loadbalancer.server.port=8501"

networks:
  proxy:
    name: proxy
    external: true
